### ISSUE TITLE
Testcommand mit und ohne Abbruchkommando für das komplette Tab

### ISSUE THREAD

**Issue by Oerny80** [fhm84/jexunit#5]
Einem Testcommand soll es möglich sein zu sagen, ob die Folgekommands noch sinnvoll ausgeführt werden können oder nicht.

**Comment by fhm84** [comment]
New feature "Fast fail" implemented.
For each test-command, there is a parameter fastFail. Set this to "true" will, if the command fails, skip all following commands of the current worksheet.
