### ISSUE TITLE
Logo is missing - Proposal

### ISSUE THREAD

**Issue by Knarzbob** [fhm84/jexunit#7]
This tool needs a logo. Therefore I am proposing my design – vector image available.

![logo_jexunit 1000px](https://user-images.githubusercontent.com/13744542/28724672-21566ff6-73bb-11e7-877b-9f2da623d76c.png)

**Comment by mesche** [comment]
Great

**Comment by fhm84** [comment]
Great!
Added it ;)
Thank you very much! #
